[package]
name = "oxidecord"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = "0.2.2"
gpui-component = "0.4.0"
anyhow = "1.0.100"
twilight-http = "0.17"
twilight-model = "0.17"
tokio = { version = "1.48.0", features = ["full"] }
gpui-router = "0.2.7"
